In [1]:
import numpy as np
import random
from time import sleep

def create_board():
    return(np.array([[0, 0, 0],
                     [0, 0, 0],
                     [0, 0, 0]]))

def possibilities(board):
    l = []
    for i in range(len(board)):
        for j in range(len(board)):
            if board[i][j] == 0:
                l.append((i, j))
    return l

def random_place(board, player):
    selection = possibilities(board)
    current_loc = random.choice(selection)
    board[current_loc] = player
    return board

def row_win(board, player):
    for x in range(len(board)):
        win = True
        for y in range(len(board)):
            if board[x, y] != player:
                win = False
                continue
        if win == True:
            return win
    return win

def col_win(board, player):
    for x in range(len(board)):
        win = True
        for y in range(len(board)):
            if board[y][x] != player:
                win = False
                continue
        if win == True:
            return win
    return win

def diag_win(board, player):
    win = True
    y = 0
    for x in range(len(board)):
        if board[x, x] != player:
            win = False
    if win:
        return win
    
    win = True
    for x in range(len(board)):
        y = len(board) - 1 - x
        if board[x, y] != player:
            win = False
    return win

def evaluate(board):
    winner = 0
    for player in [1, 2]:
        if (row_win(board, player) or col_win(board, player) or diag_win(board, player)):
            winner = player
    if np.all(board != 0) and winner == 0:
        winner = -1
    return winner

def play_game():
    board, winner, counter = create_board(), 0, 1
    print(board)
    sleep(2)
    while winner == 0:
        for player in [1, 2]:
            board = random_place(board, player)
            print("Board after " + str(counter) + " move")
            print(board)
            sleep(2)
            counter += 1
            winner = evaluate(board)
            if winner != 0:
                break
    return winner

print("Winner is: " + str(play_game()))


[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[0 0 0]
 [0 0 1]
 [0 0 0]]
Board after 2 move
[[0 0 0]
 [2 0 1]
 [0 0 0]]
Board after 3 move
[[0 0 1]
 [2 0 1]
 [0 0 0]]
Board after 4 move
[[2 0 1]
 [2 0 1]
 [0 0 0]]
Board after 5 move
[[2 0 1]
 [2 1 1]
 [0 0 0]]
Board after 6 move
[[2 0 1]
 [2 1 1]
 [0 2 0]]
Board after 7 move
[[2 1 1]
 [2 1 1]
 [0 2 0]]
Board after 8 move
[[2 1 1]
 [2 1 1]
 [2 2 0]]
Winner is: 2


In [2]:
from collections import deque

def bfs(start_state):
    target = [1, 2, 3, 4, 5, 6, 7, 8, 0]
    dq = deque([start_state])
    visited = {tuple(start_state): None}
    
    while dq:
        state = dq.popleft()
        
        if state == target:
            path = []
            while state:
                path.append(state)
                state = visited[tuple(state)]
            return path[::-1]
        
        zero = state.index(0)
        row, col = divmod(zero, 3)
        
        # Valid moves are: up (-3), down (+3), left (-1), right (+1)
        for move in (-3, 3, -1, 1):
            new_zero = zero + move
            
            # Check if the move is within bounds and the movement is valid
            new_row, new_col = divmod(new_zero, 3)
            if 0 <= new_row < 3 and 0 <= new_col < 3 and abs(row - new_row) + abs(col - new_col) == 1:
                # Swap the zero with the new position
                neighbor = state[:]
                neighbor[zero], neighbor[new_zero] = neighbor[new_zero], neighbor[zero]
                
                if tuple(neighbor) not in visited:
                    visited[tuple(neighbor)] = state
                    dq.append(neighbor)
    
    return None

def printSolution(path):
    for state in path:
        print("\n".join(' '.join(map(str, state[i:i+3])) for i in range(0, 9, 3)), end="\n-----\n")

startState = [1, 3, 0, 6, 8, 4, 7, 5, 2]
solution = bfs(startState)

if solution:
    printSolution(solution)
    print(f"Solved in {len(solution) - 1} steps.")
else:
    print("No solution found.")


1 3 0
6 8 4
7 5 2
-----
1 3 4
6 8 0
7 5 2
-----
1 3 4
6 8 2
7 5 0
-----
1 3 4
6 8 2
7 0 5
-----
1 3 4
6 0 2
7 8 5
-----
1 3 4
0 6 2
7 8 5
-----
1 3 4
7 6 2
0 8 5
-----
1 3 4
7 6 2
8 0 5
-----
1 3 4
7 0 2
8 6 5
-----
1 3 4
7 2 0
8 6 5
-----
1 3 0
7 2 4
8 6 5
-----
1 0 3
7 2 4
8 6 5
-----
1 2 3
7 0 4
8 6 5
-----
1 2 3
7 4 0
8 6 5
-----
1 2 3
7 4 5
8 6 0
-----
1 2 3
7 4 5
8 0 6
-----
1 2 3
7 4 5
0 8 6
-----
1 2 3
0 4 5
7 8 6
-----
1 2 3
4 0 5
7 8 6
-----
1 2 3
4 5 0
7 8 6
-----
1 2 3
4 5 6
7 8 0
-----
Solved in 20 steps.
